### PR TITLE
Added -e -q -m parameters. Added binary file output and separate metadata text file.

### PR DESCRIPTION
**Pull request by mariocannistra**
Hello Klemen, Andrej.
I recently made some change/additions to your wonderful program rtl-power-fftw in order to leverage it on the Raspberry PI where I need to save the power values in a continuous way for scan sessions lasting for example 30 minutes.
Please see my project here: [https://www.hackster.io/mariocannistra/radio-astronomy-with-rtl-sdr-raspberrypi-and-amazon-aws-iot-45b617](https://www.hackster.io/mariocannistra/radio-astronomy-with-rtl-sdr-raspberrypi-and-amazon-aws-iot-45b617)

For the output I wanted to use a binary format instead of the .csv one in order to:
- obtain the smallest possible size since I'm logging all the night long (CSV's blank delimiters and decimal dots were wasting my precious microSD space)
- keep high the precision on decimal digits saving float values
- obtain a complete stream of binary values representing all the bins for each scan, one scan after the other...
- ...that would allow me to plot the waterfall extremely fast with gnuplot
- ...and then add specific annotations in a more convenient way using python

I added the following command line parameters:
-e param for session duration
	this allows to specify the recording duration in sec, mins... etc
-q flag to limit verbosity
	this will allow the various printouts to happen only the first time, to limit my execution log size
-m param to produce binary matrix output and separate metadata file
	this will get a filename (without extension) and use it to store the power values in binary format within a .bin file + a metadata text file with .met extension

I tried following your coding approach as much as possible and merged the new params in your alphabetical order.
	
Please note that a double was used to store the power value, but that was 8 bytes per value in binary format. I changed that to a float that is only 4 bytes per value and cuts the file size in half. The available precision should still be enough for many usages i think. Very important for me since the Raspberry PI writes on a microSD...

I think the overall result is great since I can finally leverage the ability of your software to specify N average values to integrate for less than 1 second when needed. Plus running multi-MHz scans and storing for several minutes.... all together.

My last desire would actually be the ability to specify a crop percentage but did not have so much time until now. Will see...

Example usage python programs are here: [https://github.com/mariocannistra/radio-astronomy-fftw](https://github.com/mariocannistra/radio-astronomy-fftw)

Kind regards,
Mario

### CODE REVIEW

**Comment by KlemenBlokar** [comment]
Hi,

thank you very much for your contribution.
We will definitely try to merge in your efforts, because the intention is to 
provide a solution for every sensible need that anyone can come up with.

We will review the code (hopefully soon after the Easter) and see if anything 
needs further refinement before merging in (for example, I would like to see 
the long option names of parameters inculed beside their description in the 
manual).

All in all, I find your additions really useful, so I'm sure we will come to a 
satisfactory situation where they will find place in rtl_power_fftw.

You have a great project webpage, it's a very interesting read.

If you are curious, this is a little bit of information about the project that 
brought rtl_power_fftw to life:
http://www.ad-vega.si/en/articles/radio-telescope-at-gymnasium-sentvid/

We are also in the middle of revamping the code to make use of the extra
cores that raspberrypi has recently been blessed with. I cannot promise when
we will have the reworked version ready, but we will get there. 

Best regards,
Klemen

Dne petek, 25. marec 2016 ob 09:11:21 je Mario Cannistr� napisal(a):

**Comment by mariocannistra** [comment]
Thank you Klemen.
Few minutes ago I've installed pandoc, completed the manual source, generated and tested the man file. Also long option names are now present.  

I've received a request to have also an option for linear power values instead of logarithmic.  I've added option -l --linear for this purpose.  

I've also bumped the internal version string to "1.0-beta2".  

This new release contains also a small bugfix for missing empty line to mark the end of a measurement set in console output.

I've read your article about the radio-telescope: that is really cool ! A true antenna to work at the H line frequency ! I've too many space and time constraints for that and will probably remain a dream for some more time.  
You will be interested to know that I've added the -l option on request by Wolfgang Herrmann that is heading the operations at the "Astropeiler Stockert". This is a radio telescope facility which was formerly operated by the University of Bonn and the Max Planck Institute for Radio Astronomy.  
Now is operated by amateurs and you can read some more here:  http://astropeiler.de/  

Cheers,  
Mario

**Comment by mariocannistra** [comment]
Hello Klemen, Andrej.
Thank you for accepting/merging my changes.
Cheers,
Mario

**Comment by alajovic** [comment]
Hi Mario,

I have only now gotten the time to test your matrix output mode and I do have a few concerns about the implementation. I'll list them here first and then we can also open a separate issue later in order to deal with them.

1) Frequency scanning is not taken into account. In the metafile, there are fields "startFreq", "endFreq" and "stepFreq", which implies that the frequencies corresponding to the data are monotonously increasing. This is not necessarily the case. By a rule, if frequency scanning is performed, subsequent frequency bands can easily overlap (even more so if the --overlap option is used). The existing metafile does not contain enough information to recover the actual frequencies scanned during the measurement.

2) There is no detection of skipped (untunable) frequency bands. Certain RTL USB dongles have "holes" in their frequency range and if such a hole is encountered, the program drops such a frequency from the list of scanned frequencies. The code for matrix output only looks at the list of center frequencies once per program run (by the way: why is this done in the main loop and not before it, if it just needs to be done once?) and it does so at a point when all of the frequencies have not even been probed yet. If a certain frequency happens to fall into a dead range of the receiver and is removed, the number of samples per scan in the metafile will be wrong. Also note that any frequency can be dropped at any point during the run, not just during the first pass. The mode with text ouput has no problems dealing with this as it can omit the output of the dropped frequency bands from any point on. However, in matrix mode, this is going to be a problem since there must be a constant amount of data written per pass, otherwise the data will be misaligned and unreadable.

3) You have changed the accumulator type from double to float. I am quite uneasy about this. Floats have a dynamic range of somewhere over 1e7: for example, if you add 2e7 + 1 in float precision, the result will be 2e7. That is, the result will be exactly the same as if you had not added the 1. The same happens if you try to add 10 to 2e8 or 100 to 2e9 or anything along this line; if the two numbers differ in magnitude by more than approximately 1e7, the result is completely wrong. Now, in the program, we are accumulating a large number of values that have approximately the same magnitude. This means that once we have added 1e7 such samples in float arithmetic, the result will not increase anymore - at all! With a sample rate of 2e6 Hz and 512-bin FFT, there are about 3906 spectra added per second and thus 1e7 spectra will be added in just over 42 minutes. This is not an unreasonable integration time for, say, radio astronomy. So the accumulation MUST be by all means done in double arithmetic. Once the accumulated values are divided by the number of measurements, such a high precision is not needed anymore and the results can be cast into floats before being written to the file.

4) Running `rtl_power_fftw -m test -f 100M:108M`, I get a `test.met` file with (amongst others) the following lines:

    inf # avgScanDur (sec)

Looks like a division by zero somewhere.

    160408213514 # firstAcqTimestamp UTC
    160408213516 # lastAcqTimestamp UTC

I have no idea what these values are. They are certainly not Unix time:

    $ date --date='@160408213514'
    Fri Feb 18 14:05:14 CET 7053

cheers,
andrej

**Comment by alajovic** [comment]
Hi again,

in the mean time, I have figured out what the firstAcqTimestamp and lastAcqTimestamp values are (they are just a concatenation of date and time without any delimiters), but while looking at the code that produces them, I noticed that there is an unwanted side-effect to setting the matrix output: namely, the format of the timestamps in the diagnostic output (stderr) are also altered. Running in text mode mode, I get this:

    $ rtl_power_fftw -f 100M
    [...]
    Acquisition started at 2016-04-09 11:30:32 UTC
    Acquisition done at 2016-04-09 11:30:32 UTC

but running in matrix mode, I get this:

    $ rtl_power_fftw -m test -f 100M
    [...]
    Acquisition started at 160409113037
    Acquisition done at 160409113037

The choice of the output mode is clearly affecting the diagnostic output as well.

**Comment by mariocannistra** [comment]
Hello Andrej.
I'm traveling at the moment but this evening I will reply with more detail.  
3) you are absolutely right and I will revert to original format and convert before saving.  
1) I think will be covered by new option for cropping that I'm testing and almost ready to release. This gives contiguous bins without aliases and monoton freq increase. I saw what you mean after running some night long scans. Now the results seem really better. Will expand on this......  
2) I originally produced a text matrix file then hit by the huge size I switched to binary with some constraint due to how gnuplot works. I think making this change I left behind code in wrong place. Also I was planning to produce a separate .frq file that is still in the source but commented out.  
4) never got the divide by zero during my tests. At this point I will repeat all of them taking care also of the time string and the altered value you show in second message.  
I think my test scripts don't include the simpler option sets with which you spotted the issues.  Will work on this.  
Will write you later.  
Mario

**Comment by alajovic** [comment]
Hi Mario,

thanks for replying, I am looking forward to discussing this so we can come to a satisfying solution. Just a word of caution about the following:

> 1) I think will be covered by new option for cropping that I'm testing and almost ready to release. This gives contiguous bins without aliases and monoton freq increase.

A crop option was discussed before (see issue #3) and I am not in favour of it because I believe that it belongs into a post-processor. One of the principal design decisions for rtl_power_fftw was that it should, so to say, "tell the truth, the whole truth and nothing but the truth". What I mean by this is that it should not do any operations that would irreversibly transform the data (aside from averaging the power spectra, of course). This adheres to the Unix principle: to have a tool that does one thing and does it well. rtl_power_fftw is a data gathering program. I believe that the data obtained in a measurement should be the data presented to the user, without omissions. The user can then decide on what to do with it. Cropping the spectra involves data loss and _only_ the user knows how (and if) this should be done in their specific case. For example: which part of the overlapping data should remain? The one from the lower frequency spectrum? The one from the higher? Half of both? There is no _right_ answer here and my standpoint is that if there is no decidedly right way of doing it, we should not do it. It also complicates things such as baseline correction. If the data is stored unaltered, there is always a possiblity to do the correction later, or even to _undo_ the correction already done with the --baseline option and apply a different one. With cropped data, such an operation is much more challenging.

cheers,
andrej

**Comment by mariocannistra** [comment]
Hello Andrej.
About items 3 and 4, I've just commited the following:
- fix: division by zero when using matrix mode with single scan  
- change: firstAcqTimestamp and lastAcqTimestamp are now using the same time format of debug statements per original version  
- revert: pwrdb format is a double per original version, converted to float for binary output  
This version does not contain yet the other changes I previously mentioned. I will answer separately about items 1 and 2 when I have a bit more of time.  
cheers,
Mario

**Comment by alajovic** [comment]
Hi Mario,

thanks, I'll check the fix and merge it; perhaps even today, but more likely tomorrow.

I was also deliberating the other points that have been mentioned (crop function etc.) and I have come to an idea that I think would solve everything rather elegantly. As @KlemenBlokar has already mentioned, I have been lately working on a quite heavy internal reorganization of rtl_power_fftw (with support for multiple FFT threads). The branch has been private until now because at times the code was quite in a messy state and I did not want to have a public version that I knew contained a, say, nasty race condition. Anyway. As a consequence of this overhaul, it is now much easier to support multiple output formats, and I thought about the following possibility:

* We devise an "intermediate binary output format". It would, roughly, consist of a header with metadata, a dump of the acquisition plan, and frames containing the actual data. Everything would be packed into one binary stream, so there would be no need for separate metadata. Being an intermediate format, it could also perfectly well be platform-specific (no need to take care of endianness, for example).

* This data stream could be either sent to stdout or stored to a file (but the program would object if the output was a tty - there is really no point in dumping binary data to a terminal).

* Since a binary stream is very efficient writing- and reading-wise, postprocessors could now be easily implemented in just about any programming language. So, for example, there could be a postprocessor that expected the intermediate binary format as an input; it would then analyze the data, crop the overlapping spectra per user's need, and store the result in whatever format the user deems suitable. For example:

        rtl_power_fftw -f 100M --binary |crop_postprocessor >output.dat

    I have made up the `--binary` flag as an example, but this is the central idea. If the postprocessor also had an option for outputting the intermediate binary format, multiple postprocessors could also be chained.

I think such an approach would be very useful and quite easily implemented.

**Comment by mariocannistra** [comment]
Hi Andrej.  
Sorry for the delayed answer, these days I'm quite busy.  
I'm very aligned with the approach that you described.  

Just a bit of background: more than one year ago, when keenerd made the Indiegogo funded sprint ([https://www.indiegogo.com/projects/a-month-of-rtl-sdr#/story](https://www.indiegogo.com/projects/a-month-of-rtl-sdr#/story)) I contributed some of the requirements about radio-astronomy ([http://igg.kmkeen.com](http://igg.kmkeen.com)/).  At the time I considered HDF5 to store metadata and power values in a binary format that is well known and compatible with several scientific packages.
At the moment I'm using the matrix dump of floats that you've seen just because I'm specifically targeting the Raspberry PI and using gnuplot there has its own constraints.   But HDF5 conversion is already going on in one of the new python programs that I will soon release. I'm also working on a multithreaded rendering program that will allow me to eliminate gnuplot from my post-scan processing pipeline. Gnuplot and the 1 GB of ram on the R-PI are a difficult env to live within.  

That is why I'm perfectly fine with your approach, working on the intermediate format, to then post-process, either to "export" to standard format or to "crop", etc  

Also, the multithreaded change you are working on is a super one to leverage the R-PI 2 and 3 capabilities. If you need a beta tester I'm here :-)  

Now, my only concern is that I would like to give continuity to my main project since there are already some people around the globe building their amateur radio astronomy observatory using my hackster project + rtl_power_fftw + python programs  

My proposal is: I would release my latest version with the current binary matrix + cropping feature so that both me and those people can continue with our work, but in parallel, I would contribute to the approach you described in some way (if you need/like). I think some time will be needed to release the first two main programs (let's say the new multithreaded rtl_power_fftw and a cropping post-processor )... when they will be ready, I will adapt my set of python programs to use the new rtl_power_fftw "suite" and contextually abandon development of my "temporary" version.  

Since I already have an HDF5 conversion program in the works, I would adapt that one as well.  

I think the list of metadata I currently have (not published yet) could be a starting point or a contribution to a similar list you probably have.  At the moment I'm also embedding the metadata inside the PNG properties (similar to EXIF in JPEGs...) and I would keep this aligned.  This way anyone receiving just a spectrogram PNG could know everything about how it has been obtained.  

One note about pipe vs file: all the fast operations I've used until today are NumPy / file / nparray based and I'm not sure if I could have same perf with pipe input on python. I should just investigate it and for the moment I would prefer a file based output.  

If you need to contact me privately, my email is on my github profile page.

Please let me know your thoughts.

Cheers,
Mario

**Comment by alajovic** [comment]
Hey Mario,

I was on a business trip for the past few days, hence a bit of a delayed answer also from me. But we are not in a hurry, after all. :-)

I see that we are very much thinking along the same lines because I have also been considering HDF5 as the storage format for rtl_power_fftw. Actually, this had already been quite an early idea when we were concieving the program, but then we settled on a text-based format for a start, leaving HDF5 output to be implemented later.

> Now, my only concern is that I would like to give continuity to my main project since there are already some people around the globe building their amateur radio astronomy observatory using my hackster project + rtl_power_fftw + python programs

This is a perfectly reasonable concern. I think that the best way to deal with this is for you to maintain a dedicated fork with all the features that you need for your project. I have absolutely no problem with that - it's exactly what forks are intended for. It also gives you more liberty for experimenting. You just have to make it clear that anyone using your suite of programs must also fetch and install your fork of rtl_power_fftw. And as you said: once we get our reworked version up to the point where the intermediate format is working, you can modify your set of programs and release a new version to the public, obsoleting the need for a separate fork. Of course, we stay in touch in the mean time so we can discuss any ideas, problems (etc.) that come up. I have found your ideas quite sound and I am happy to hear your opinion on anything that influences your project.

> One note about pipe vs file: all the fast operations I've used until today are NumPy / file / nparray based and I'm not sure if I could have same perf with pipe input on python. I should just investigate it and for the moment I would prefer a file based output.

The choice between a pipe and a file would be entirely on the users's side (just as it is now with the text output): the intermediate format could be either piped into a program or redirected to a file. For file-based access from Python, it's then just a matter of writing a function that opens the file, parses the header, identifies where the raw data is, allocates a NumPy array, and then loops through the data slices, loading the raw data in each of them with NumPy.

**Comment by alajovic** [comment]
By the way, I have just pushed the reworked version into 'testing' branch.

**Comment by mariocannistra** [comment]
Ok, great.
I just pushed my commit with latest changes about crop percentage. I'm still testing but seems working very fine with 30% on a 20 MHz wide scan. Using the FM for tests I've seen that aliases are almost always present on both upper and lower sides of each scan. With the crop, the waterfalls are now really ... beautiful!  :-)
About Python/NumPy: I did some tests and could also be even easier than that. I'm already loading the whole file and then reshaping (extremely fast). The header structure can be declared in advance and actually read and parsed at the same time.
I'm preparing the list of metadata that I've collected / used until now. Will ping you soon.
Cheers,
Mario

**Comment by alajovic** [comment]
Hi Mario,

I have merged your commit that fixes division by zero etc. As explained before, I will leave out the commit that introduces the crop function, so what we have now is basically the department point of your fork. If any fixes/improvements appear on your side that are also applicable to our version, let me know and I'll cherry-pick them into the master branch. In parallel, we work on implementing the idea with the intermediate format + postprocessors on the testing branch.

cheers,
andrej

**Pull request merged**
